# Generated by Django 5.2 on 2025-05-21 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BizEventBizId', models.IntegerField(verbose_name='Business ID')),
                ('BizEventTitle', models.CharField(max_length=255)),
                ('BizEventStartDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('BizEventEndDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('BizEventLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('BizEventType', models.CharField(choices=[('Career & Professional', 'Career & Professional Events'), ('Entertainment & Cultural', 'Entertainment & Cultural Events'), ('Educational & Training', 'Educational & Training Events'), ('Health & Wellness', 'Health & Wellness Events'), ('Art & Lifestyle', 'Art & Lifestyle Events'), ('Sports & Recreational', 'Sports & Recreational Events'), ('Business & Marketing', 'Business & Marketing Events'), ('Community & Social', 'Community & Social Events')], max_length=50)),
                ('BizEventMode', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical')], max_length=10)),
                ('BizEventPriceModel', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=10)),
                ('BizEventPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('BizEventPaymentType', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10, null=True)),
                ('BizEventRegistrationForm', models.JSONField(default=dict)),
                ('BizEventAttendance', models.JSONField(default=dict)),
                ('BizEventRegistrationLink', models.URLField(blank=True, max_length=500, null=True)),
                ('BizEventSelfAttendanceLink', models.URLField(blank=True, max_length=500, null=True)),
                ('BizEventStatus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventMbrCard', models.BigIntegerField(verbose_name='Member Card Number')),
                ('BasicInformation', models.JSONField(default=dict)),
                ('CareerObjectivesPreferences', models.JSONField(default=dict)),
                ('EducationDetails', models.JSONField(default=dict)),
                ('WorkExperience', models.JSONField(default=dict)),
                ('SkillsCompetencies', models.JSONField(default=dict)),
                ('AchievementsExtracurricular', models.JSONField(default=dict)),
                ('OtherDetails', models.JSONField(default=dict)),
                ('EventRegistrationData', models.JSONField()),
                ('EventAttended', models.BooleanField(default=False)),
                ('EventRegistered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='event_business.bizevent')),
            ],
        ),
    ]
