# Generated by Django 5.2 on 2025-08-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_business', '0002_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temp_users', to='event_business.bizevent'),
            preserve_default=False,
        ),
    ]
