# Generated by Django 5.2 on 2025-08-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_business', '0003_tempuser_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='boothintraction',
            field=models.JSONField(default=dict),
        ),
    ]
